-- MySQL Script generated by MySQL Workbench
-- Fri Jan 27 08:00:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_donation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_donation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_donation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_donation` ;

-- -----------------------------------------------------
-- Table `db_donation`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_donation`.`tb_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `perecivel` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_donation`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_donation`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ultimo_nome` VARCHAR(50) NULL DEFAULT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipo_usuario` VARCHAR(10) NULL DEFAULT 'doador',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_donation`.`tb_doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_donation`.`tb_doacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_doacao` DATETIME NOT NULL,
  `valor` DECIMAL(8,2) NULL DEFAULT '0.00',
  `id_categoria` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `tb_doacao_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_donation`.`tb_usuario` (`id`),
  CONSTRAINT `tb_doacao_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_donation`.`tb_categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
